### ISSUE TITLE
datamodels.open does not work on a datamodel

### ISSUE THREAD

**Issue by zonca** [oirlab/liger_iris_pipeline#60]
The workaround is this commit:

https://github.com/oirlab/liger_iris_pipeline/pull/58/commits/701a431a0ed01e138776ab4098ed29cb513c353f

this is triggered by `get_reference_file`, see below for more details. It seems like JWST has no issues passing a Data model to get_reference_file, however, it seems we can only pass a string. We need to understand where this issue is coming from.

> * [701a431](https://github.com/oirlab/liger_iris_pipeline/commit/701a431a0ed01e138776ab4098ed29cb513c353f) I see how this stems from an assumption that `get_reference_file` expects a filename, not a DataModel. Should we override `get_reference_file` to accept both?

There is something I do not understand here, maybe you can track it down,
see here:
https://github.com/spacetelescope/jwst/blob/10501f22def0460b15df65cd5261601c6a71d7cf/jwst/dark_current/dark_current_step.py#L32

they are doing the same, feeding the input model to get_reference_file, why does it work for them and not for us?
I think that at some point in the class hierarchy we are using different classes but have not understood where.

_Originally posted by @zonca in https://github.com/oirlab/liger_iris_pipeline/issues/58#issuecomment-2181593872_

**Comment by astrobc1** [comment]
@zonca So I tracked the issue down to here:

https://github.com/spacetelescope/stdatamodels/blob/ee4756ffe9ff71c1fb7b067f8998949a88d6a703/src/stdatamodels/jwst/datamodels/util.py#L103-L105:

```
elif isinstance(init, model_base.JwstDataModel):
    # Copy the object so it knows not to close here
    return init.__class__(init, **kwargs)
```

which is missed since we don't subtype from `JwstDataModel`, and is how jwst gets away with passing filenames and `DataModel`s to `Step.get_reference_file` -> `Step.open_model` -> `Step._datamodels_open` -> `stdatamodels.jwst.datamodels.util.open`. Although I don't understand the utility in reinstantiating the data model with new `kwargs`.

Regardless, I think your approach #68 is the cleanest solution without patching `stdatamodels`, and that the utility in declaring such base objects for Liger and IRIS will only grow. I'll review #68 shortly.

**Comment by zonca** [comment]
@astrobc1 thanks for tracking this down!!!

I am wondering if we should just subclass `JwstDataModel`

**Comment by astrobc1** [comment]
We already override the one important property `crds_observatory` in `LigerIrisDataModel`, so that's the simplest solution I think. I'm fine with it!
