### ISSUE TITLE
Port NormalizeStep

### ISSUE THREAD

**Issue by zonca** [oirlab/liger_iris_pipeline#61]
@astrobc1 would you like to try porting one of the steps?

I recommend `NormalizeStep`.

So you can start by turning the notebook https://github.com/oirlab/liger_iris_pipeline/blob/master/liger_iris_pipeline/tests/test_normalize.ipynb into a Python file.

Then updating it to use `liger_iris_pipeline` naming, see `test_dark.py` as an example, then dig into `datamodels` and the step implementation itself to get it to work.

It is also useful to go and look at the implementation of the same step in JWST.

We want to keep each Pull Request highly focused, so do not touch any file unrelated to `NormalizeStep`.

**Comment by astrobc1** [comment]
@zonca `NormalizeStep` should be good to go / tests pass in the new branch normalize_step_port. One notable change is also normalizing the data model's `err` attribute - I think that's a safe assumption for now. Otherwise, I couldn't find a corresponding normalization step in jwst or stcal; it might be trivial enough not to warrant a whole step. This step doesn't require CRDS, so it was a good one to start with :)

Should I create a PR and assign you to review?

**Comment by zonca** [comment]
Yes, please!

**Comment by zonca** [comment]
closed by #62
